package me.rerere.workspace

import android.util.Log
import java.io.File
import java.io.RandomAccessFile
import java.nio.file.Files

class RootfsPatcher {
    fun patch(
        linuxDir: File,
        options: RootfsPatchOptions = RootfsPatchOptions(),
    ) {
        val etcDir = File(linuxDir, "etc")
        if (!etcDir.isDirectory) return

        ensureRootfsDns(etcDir, options.nameservers)
        ensureHosts(etcDir, options.hostname)
        ensureHostname(etcDir, options.hostname)
        ensureLocale(etcDir, options.locale)
        ensureGroupNames(etcDir, options.groupIds.ifEmpty { currentSupplementaryGroupIds() })
        ensureTempDirs(linuxDir)
        ensureShellEnvironment(linuxDir, options.hostname)
        ensureNpmConfig(linuxDir)
        ensureGitConfig(linuxDir)
        ensureInputrc(linuxDir)
        ensureSshConfig(linuxDir)
        ensureGlobalGitignore(linuxDir)
        ensureDoctorScript(linuxDir)
        ensureTimezone(linuxDir)
        ensureAptMirror(linuxDir)
        ensureApkMirror(linuxDir)
    }

    private fun ensureRootfsDns(
        etcDir: File,
        nameservers: List<String>,
    ) {
        val resolvConf = File(etcDir, "resolv.conf")
        // 总是重写: 镜像自带的 resolv.conf 可能指向构建环境的内网 DNS(已失效),
        // 且系统 DNS 会随网络切换变化, 每次 patch 都应刷新为当前可用的解析器
        if (resolvConf.exists() || Files.isSymbolicLink(resolvConf.toPath())) {
            resolvConf.delete()
        }

        val servers = nameservers
            .filter { it.isNotBlank() }
            .distinct()
            .take(MAX_DNS_SERVERS)
            .ifEmpty { DEFAULT_DNS_SERVERS }

        resolvConf.writeText(
            buildString {
                appendLine("# Generated by RikkaHub workspace.")
                servers.forEach { appendLine("nameserver $it") }
                appendLine("options edns0 trust-ad")
            }
        )
        verifyWrite(resolvConf, "resolv.conf (DNS)")
    }

    private fun ensureHosts(etcDir: File, hostname: String) {
        val hosts = File(etcDir, "hosts")
        val hostsContent = if (hosts.isFile) hosts.readText() else ""
        val lines = hostsContent.lineSequence().toList()
        val hasIpv4Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "127.0.0.1" && "localhost" in normalized.drop(1)
        }
        val hasIpv6Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "::1" && "localhost" in normalized.drop(1)
        }
        if (hasIpv4Localhost && hasIpv6Localhost) return

        hosts.parentFile?.mkdirs()
        hosts.appendText(
            buildString {
                if (hostsContent.isNotEmpty() && !hostsContent.endsWith('\n')) {
                    appendLine()
                }
                if (!hasIpv4Localhost) {
                    append("127.0.0.1 localhost")
                    if (hostname.isNotBlank() && hostname != "localhost") {
                        append(" ")
                        append(hostname)
                    }
                    appendLine()
                }
                if (!hasIpv6Localhost) {
                    appendLine("::1 localhost ip6-localhost ip6-loopback")
                }
            }
        )
    }

    private fun ensureHostname(etcDir: File, hostname: String) {
        val target = File(etcDir, "hostname")
        if (target.isFile && target.readText().trim().isNotBlank()) return
        target.writeText("${hostname.ifBlank { DEFAULT_HOSTNAME }}\n")
    }

    private fun ensureLocale(etcDir: File, locale: String) {
        val defaultDir = File(etcDir, "default").apply { mkdirs() }
        val target = File(defaultDir, "locale")
        val lines = if (target.isFile) target.readLines().toMutableList() else mutableListOf()
        if (lines.any { it.trim().startsWith("LANG=") }) return
        lines += "LANG=$locale"
        target.writeText(lines.joinToString(separator = "\n", postfix = "\n"))
    }

    private fun ensureGroupNames(etcDir: File, groupIds: List<Long>) {
        val target = File(etcDir, "group")
        if (!target.exists()) {
            target.writeText("root:x:0:\n")
        }
        val text = target.readText()
        val lines = text.lines()
        val existingIds = lines.mapNotNull { line ->
            line.split(':').getOrNull(2)?.toLongOrNull()
        }.toSet()
        val existingNames = lines.mapNotNull { line ->
            line.substringBefore(':').takeIf { it.isNotBlank() }
        }.toSet()
        val additions = groupIds
            .filter { it > 0 && it !in existingIds }
            .distinct()
            .map { id ->
                val baseName = "android_gid_$id"
                val name = if (baseName in existingNames) "${baseName}_workspace" else baseName
                "$name:x:$id:"
            }
        if (additions.isEmpty()) return

        target.appendText(
            buildString {
                if (text.isNotEmpty() && !text.endsWith('\n')) {
                    appendLine()
                }
                additions.forEach { appendLine(it) }
            }
        )
    }

    private fun ensureTempDirs(linuxDir: File) {
        listOf("tmp", "var/tmp", "root").forEach { path ->
            File(linuxDir, path).mkdirs()
        }
        listOf(File(linuxDir, "tmp"), File(linuxDir, "var/tmp")).forEach { dir ->
            dir.setReadable(true, false)
            dir.setWritable(true, false)
            dir.setExecutable(true, false)
        }
        File(linuxDir, "root").apply {
            setReadable(true, true)
            setWritable(true, true)
            setExecutable(true, true)
        }
    }

    private fun currentSupplementaryGroupIds(): List<Long> {
        val status = File("/proc/self/status")
        if (!status.isFile) return emptyList()
        val groups = status.readLines().firstOrNull { it.startsWith("Groups:") } ?: return emptyList()
        return groups
            .removePrefix("Groups:")
            .trim()
            .split(WHITESPACE_REGEX)
            .mapNotNull { it.toLongOrNull() }
    }

    private fun ensureShellEnvironment(linuxDir: File, hostname: String) {
        val profileD = File(linuxDir, "etc/profile.d").apply { mkdirs() }
        val rikkahubSh = File(profileD, "rikkahub.sh")
        // 模板带版本标记 rk-ext:N; 低于当前版本的旧模板整体重写升级
        if (!rikkahubSh.isFile || !rikkahubSh.readText().contains(SHELL_ENV_VERSION_MARKER)) {
            rikkahubSh.writeText(
                buildString {
                    appendLine("# RikkaHub workspace environment")
                    appendLine("# $SHELL_ENV_VERSION_MARKER")
                    appendLine("export PATH=\"/usr/local/bin:\$PATH\"")
                    appendLine("export EDITOR=nano")
                    appendLine("export PS1='\\[\\e[1;32m\\]${hostname}\\[\\e[0m\\]:\\[\\e[1;34m\\]\\w\\[\\e[0m\\]\\$ '")
                    appendLine("alias ll='ls -la'")
                    appendLine("alias la='ls -A'")
                    appendLine("alias l='ls -CF'")
                    appendLine("# --- 可扩展性/跨设备共享: /config 为宿主侧挂载区, 内容随 /config 同步 ---")
                    appendLine("# 用户自定义 shell 扩展: 每个脚本独立容错加载")
                    appendLine("if [ -d /config/profile.d ]; then")
                    appendLine("  for __rk_f in /config/profile.d/*.sh; do")
                    appendLine("    [ -f \"\$__rk_f\" ] && . \"\$__rk_f\"")
                    appendLine("  done")
                    appendLine("  unset __rk_f")
                    appendLine("fi")
                    appendLine("# 用户 npm 覆盖配置(优先级高于 ~/.npmrc)")
                    appendLine("if [ -f /config/npm-user.npmrc ]; then")
                    appendLine("  export NPM_CONFIG_USERCONFIG=/config/npm-user.npmrc")
                    appendLine("fi")
                    appendLine("# 简便性: /config/env 简易环境变量(每行 KEY=VALUE, # 注释), 门槛低于写 sh 脚本")
                    appendLine("if [ -f /config/env ]; then")
                    appendLine("  while IFS= read -r __rk_line || [ -n \"\$__rk_line\" ]; do")
                    appendLine("    case \"\$__rk_line\" in ''|\\#*) continue ;; esac")
                    appendLine("    case \"\$__rk_line\" in *=*) export \"\$__rk_line\" ;; esac")
                    appendLine("  done < /config/env")
                    appendLine("fi")
                    appendLine("# 多平台共享: git over SSH 使用 /config/ssh 内密钥(ed25519 优先)")
                    appendLine("if [ -d /config/ssh ]; then")
                    appendLine("  for __rk_key in /config/ssh/id_ed25519 /config/ssh/id_rsa; do")
                    appendLine("    if [ -f \"\$__rk_key\" ]; then")
                    appendLine("      GIT_SSH_COMMAND=\"ssh -i \$__rk_key -o IdentitiesOnly=yes\"")
                    appendLine("      [ -f /config/ssh/known_hosts ] && GIT_SSH_COMMAND=\"\$GIT_SSH_COMMAND -o UserKnownHostsFile=/config/ssh/known_hosts\"")
                    appendLine("      [ -f /config/ssh/ssh_config ] && GIT_SSH_COMMAND=\"\$GIT_SSH_COMMAND -F /config/ssh/ssh_config\"")
                    appendLine("      export GIT_SSH_COMMAND")
                    appendLine("      break")
                    appendLine("    fi")
                    appendLine("  done")
                    appendLine("  unset __rk_key")
                    appendLine("fi")
                    appendLine("[ -f /config/pip.conf ] && export PIP_CONFIG_FILE=/config/pip.conf")
                    appendLine("# npm 全局包装与 pip user 安装路径(目录不存在时前置无害, guard 防重复)")
                    appendLine("case \":\$PATH:\" in")
                    appendLine("  *\":/config/npm-global/bin:\"*) ;;")
                    appendLine("  *) export PATH=\"/config/npm-global/bin:/root/.local/bin:\$PATH\" ;;")
                    appendLine("esac")
                }
            )
        }

        val bashrc = File(linuxDir, "root/.bashrc")
        if (!bashrc.isFile || bashrc.readText().isBlank()) {
            bashrc.writeText(
                buildString {
                    appendLine("# RikkaHub workspace bashrc")
                    appendLine("if [ -f /etc/profile.d/rikkahub.sh ]; then . /etc/profile.d/rikkahub.sh; fi")
                    appendLine("if [ -f /etc/bash_completion ] && ! shopt -oq posix; then . /etc/bash_completion; fi")
                    appendLine("set -o vi 2>/dev/null || true")
                }
            )
        }

        val profile = File(linuxDir, "root/.profile")
        if (!profile.isFile || profile.readText().isBlank()) {
            profile.writeText(
                buildString {
                    appendLine("# RikkaHub workspace profile")
                    appendLine("if [ -f /etc/profile.d/rikkahub.sh ]; then . /etc/profile.d/rikkahub.sh; fi")
                    appendLine("if [ -f \"\$HOME/.bashrc\" ]; then . \"\$HOME/.bashrc\"; fi")
                }
            )
        }
    }

    private fun ensureNpmConfig(linuxDir: File) {
        val npmrc = File(linuxDir, "root/.npmrc")
        if (npmrc.isFile && npmrc.readText().contains("registry=")) return
        npmrc.parentFile?.mkdirs()
        npmrc.writeText(
            buildString {
                appendLine("registry=https://registry.npmmirror.com")
                appendLine("fetch-retries=3")
                appendLine("fetch-timeout=60000")
                appendLine("maxsockets=3")
                appendLine("fund=false")
                appendLine("audit=false")
                appendLine("loglevel=warn")
            }
        )
    }

    private fun ensureGitConfig(linuxDir: File) {
        val gitconfig = File(linuxDir, "root/.gitconfig")
        if (!gitconfig.isFile) {
            gitconfig.parentFile?.mkdirs()
            gitconfig.writeText(
                buildString {
                    appendLine("[user]")
                    appendLine("	name = RikkaHub Workspace")
                    appendLine("	email = workspace@rikkahub.app")
                    appendLine("[init]")
                    appendLine("	defaultBranch = main")
                    appendLine("[safe]")
                    appendLine("	directory = /workspace")
                    appendLine("[pull]")
                    appendLine("	rebase = false")
                    appendLine("[transfer]")
                    appendLine("	fsckobjects = true")
                }
            )
            verifyWrite(gitconfig, "gitconfig")
        }
        // 跨设备共享: /config 为宿主侧挂载区, 用户 git 身份/代理等放 /config/gitconfig
        // (git 对不存在的 include 文件静默忽略)
        if (!gitconfig.readText().contains("[include]")) {
            gitconfig.appendText("\n[include]\n\tpath = /config/gitconfig\n")
        }
    }

    private fun ensureInputrc(linuxDir: File) {
        val inputrc = File(linuxDir, "root/.inputrc")
        if (inputrc.isFile && inputrc.readText().contains("set editing-mode")) return
        inputrc.parentFile?.mkdirs()
        inputrc.writeText(
            buildString {
                appendLine("# RikkaHub workspace readline config")
                appendLine("set editing-mode vi")
                appendLine("set keymap vi-insert")
                appendLine("set show-mode-in-prompt on")
                appendLine("# History search: up/down arrow filter by prefix")
                appendLine("\"\\e[A\": history-search-backward")
                appendLine("\"\\e[B\": history-search-forward")
                appendLine("# Tab completion: case-insensitive, show all matches")
                appendLine("set completion-ignore-case on")
                appendLine("set show-all-if-ambiguous on")
                appendLine("set menu-complete-display-prefix on")
                appendLine("# Bell off")
                appendLine("set bell-style none")
            }
        )
    }

    private fun ensureSshConfig(linuxDir: File) {
        val sshDir = File(linuxDir, "root/.ssh").apply { mkdirs() }
        sshDir.setExecutable(true, true)
        // known_hosts 空文件（首次自动 Git clone 不因 host key 交互阻塞）
        val knownHosts = File(sshDir, "known_hosts")
        if (!knownHosts.isFile) {
            knownHosts.parentFile?.mkdirs()
            knownHosts.writeText("")
        }
        // SSH 配置：自动化操作接受新 host key，不交互
        val config = File(sshDir, "config")
        if (!config.isFile) {
            config.writeText(
                buildString {
                    appendLine("# RikkaHub workspace SSH config")
                    appendLine("Host *")
                    appendLine("    StrictHostKeyChecking accept-new")
                    appendLine("    UserKnownHostsFile /root/.ssh/known_hosts")
                    appendLine("    LogLevel ERROR")
                }
            )
        }
    }

    private fun ensureGlobalGitignore(linuxDir: File) {
        val gitignore = File(linuxDir, "root/.gitignore_global")
        if (gitignore.isFile) return
        gitignore.parentFile?.mkdirs()
        gitignore.writeText(
            buildString {
                appendLine("# RikkaHub global gitignore")
                appendLine("# Node")
                appendLine("node_modules/")
                appendLine("npm-debug.log*")
                appendLine(".npm/")
                appendLine("# Python")
                appendLine("__pycache__/")
                appendLine("*.pyc")
                appendLine("*.egg-info/")
                appendLine(".venv/")
                appendLine("# Java / Gradle")
                appendLine(".gradle/")
                appendLine("build/")
                appendLine("*.class")
                appendLine("# IDE")
                appendLine(".idea/")
                appendLine(".vscode/")
                appendLine("*.swp")
                appendLine("*.swo")
                appendLine("*~")
                appendLine(".DS_Store")
                appendLine("# Temp / cache")
                appendLine(".cache/")
                appendLine("tmp/")
                appendLine("*.tmp")
                appendLine("# OS")
                appendLine("Thumbs.db")
                appendLine(".directory")
            }
        )
        // 在 .gitconfig 中注册为 excludesfile（如尚未注册）
        val gitconfig = File(linuxDir, "root/.gitconfig")
        if (gitconfig.isFile && !gitconfig.readText().contains("excludesfile")) {
            val existing = gitconfig.readText()
            gitconfig.writeText(existing.trimEnd() + "\n[core]\n\texcludesfile = /root/.gitignore_global\n")
        }
    }

    /**
     * 一键自检脚本 /usr/local/bin/rk-doctor:
     * 工具链/网络/挂载区/磁盘/env 全量体检, PASS-FAIL 逐项输出并附修复提示。
     * 每次都重写(脚本随版本演进), 开销可忽略。
     */
    private fun ensureDoctorScript(linuxDir: File) {
        val binDir = File(linuxDir, "usr/local/bin").apply { mkdirs() }
        val doctor = File(binDir, "rk-doctor")
        doctor.writeText(DOCTOR_SCRIPT.trimIndent() + "\n")
        doctor.setExecutable(true, false)
    }

    /** rikkahub.sh 模板版本标记: 内容演进时递增, 触发已安装 rootfs 的模板升级 */
    private val SHELL_ENV_VERSION_MARKER = "rk-ext:2"

    // shebang 用 /bin/sh: Alpine minirootfs 无 bash, 脚本内容为 POSIX 语法, 两种 shell 行为一致
    private val DOCTOR_SCRIPT = """
        #!/bin/sh
        # RikkaHub workspace self-check (usage: rk-doctor)
        PASS=0; FAIL=0
        ok()  { echo "[PASS] ${'$'}1"; PASS=${'$'}((PASS+1)); }
        bad() { echo "[FAIL] ${'$'}1${'$'}{2:+ | hint: ${'$'}2}"; FAIL=${'$'}((FAIL+1)); }

        echo "===== rk-doctor ====="
        echo "-- tools --"
        for t in node npm git curl wget unzip tar gzip python3 pip3; do
          command -v "${'$'}t" >/dev/null 2>&1 && ok "${'$'}t" || bad "${'$'}t missing" "apt-get install -y ${'$'}t"
        done
        if command -v node >/dev/null 2>&1; then
          echo "  node=${'$'}(node --version 2>/dev/null) npm=${'$'}(npm --version 2>/dev/null)"
          [ -d /opt/nodejs ] && echo "  install: /opt/nodejs (mirror tarball)" || echo "  install: system package"
        fi

        echo "-- network --"
        CODE=${'$'}(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 https://registry.npmmirror.com/ 2>/dev/null)
        case "${'$'}CODE" in
          200|301|302) ok "npmmirror reachable (HTTP ${'$'}CODE)" ;;
          *) bad "npmmirror unreachable (HTTP ${'$'}{CODE:-000})" "check DNS/proxy (/etc/resolv.conf)" ;;
        esac

        echo "-- mounts --"
        for d in /workspace /skills /tool_outputs /upload /tools /config; do
          [ -d "${'$'}d" ] && ok "mount ${'$'}d" || bad "mount missing: ${'$'}d" "restart workspace session"
        done

        echo "-- extensions --"
        for f in /config/env /config/npm-user.npmrc /config/gitconfig /config/tools.txt /config/pip.conf; do
          [ -f "${'$'}f" ] && ok "config ${'$'}f"
        done
        if [ -d /config/ssh ] && ls /config/ssh/id_* >/dev/null 2>&1; then
          ok "ssh key in /config/ssh"
        elif [ -f ~/.ssh/id_ed25519 ] || [ -f ~/.ssh/id_rsa ]; then
          ok "ssh key in ~/.ssh (device-local)"
        else
          echo "[SKIP] no ssh key (hint: put id_ed25519 under /config/ssh to share across devices)"
        fi
        for s in /config/profile.d/*.sh; do
          [ -f "${'$'}s" ] && ok "profile script ${'$'}s"
        done

        echo "-- disk --"
        echo "  avail(/workspace): ${'$'}(df -h /workspace 2>/dev/null | awk 'NR==2{print ${'$'}4}')"

        echo "-- env --"
        echo "  TZ offset: ${'$'}(date +%z 2>/dev/null)  LANG=${'$'}{LANG:-unset}"
        echo "  NPM registry: ${'$'}(npm config get registry 2>/dev/null)"
        [ -n "${'$'}{PIP_CONFIG_FILE:-}" ] && echo "  PIP config: ${'$'}PIP_CONFIG_FILE"
        [ -n "${'$'}{GIT_SSH_COMMAND:-}" ] && echo "  GIT_SSH_COMMAND: ${'$'}{GIT_SSH_COMMAND%% *}-based (/config/ssh)"

        echo "====================="
        echo "result: ${'$'}PASS pass, ${'$'}FAIL fail"
        [ "${'$'}FAIL" -eq 0 ]
    """.trimIndent()

    private fun ensureTimezone(linuxDir: File) {
        val localtime = File(linuxDir, "etc/localtime")
        if (localtime.exists()) return
        val zoneinfoDir = File(linuxDir, "usr/share/zoneinfo")
        val asiaShanghai = File(zoneinfoDir, "Asia/Shanghai")
        if (asiaShanghai.isFile) {
            localtime.parentFile?.mkdirs()
            try {
                Files.createSymbolicLink(localtime.toPath(), asiaShanghai.toPath())
            } catch (e: Exception) {
                Log.w(TAG, "Failed to create timezone symlink", e)
            }
        }
        val timezoneFile = File(linuxDir, "etc/timezone")
        if (!timezoneFile.isFile || timezoneFile.readText().isBlank()) {
            timezoneFile.parentFile?.mkdirs()
            timezoneFile.writeText("Asia/Shanghai\n")
        }
    }

    private fun ensureAptMirror(linuxDir: File) {
        val etcDir = File(linuxDir, "etc/apt")
        if (!etcDir.isDirectory) return

        val oneLineFiles = (
            listOf(File(etcDir, "sources.list")) +
                File(etcDir, "sources.list.d").takeIf { it.isDirectory }
                    ?.listFiles { f -> f.isFile && f.name.endsWith(".list") }.orEmpty()
            ).filter { it.isFile }
        val deb822Files = File(etcDir, "sources.list.d").takeIf { it.isDirectory }
            ?.listFiles { f -> f.isFile && f.name.endsWith(".sources") }.orEmpty()
            .filter { it.isFile }

        // Ubuntu arm64 必须走 ubuntu-ports 档案(TUNA 的 ubuntu/ 只含 amd64/i386);
        // EOL 版本(如 25.10 questing)的包已从 ports 下架, 仅 old-releases 保留主套件快照
        val arch = detectRootfsArch(linuxDir)
        val ubuntuPath = if (arch == "x86_64" || arch == "x86") "ubuntu" else "ubuntu-ports"
        val eolUbuntu = (oneLineFiles + deb822Files).any { hasEolUbuntuSuite(it) }
        // 最小 rootfs(如 ubuntu-base)可能没装 ca-certificates, apt 走 https 会证书校验失败;
        // 探测到可信 CA 捆绑才用 https, 否则镜像统一走 http
        val scheme = if (hasTrustedCaBundle(linuxDir)) "https" else "http"
        // old-releases 直连上游(TUNA 的 ubuntu-old-releases 镜像不全, 实测缺 oracular/mantic 等);
        // 上游 old-releases.ubuntu.com 含全部架构(含 arm64)且 http/https 均可用
        val ubuntuBase = if (eolUbuntu) {
            "$scheme://old-releases.ubuntu.com/ubuntu/"
        } else {
            "$scheme://$TUNA_HOST/$ubuntuPath/"
        }

        oneLineFiles.forEach { patchOneLineSource(it, ubuntuBase, eolUbuntu) }
        deb822Files.forEach { patchDeb822Source(it, ubuntuBase, eolUbuntu) }
    }

    /** 是否具备可信 CA 捆绑(ca-certificates 包); 缺失时 apt https 会证书校验失败 */
    private fun hasTrustedCaBundle(linuxDir: File): Boolean =
        File(linuxDir, "usr/share/ca-certificates").isDirectory &&
            (File(linuxDir, "etc/ssl/certs/ca-certificates.crt").exists() ||
                File(linuxDir, "etc/ssl/certs").isDirectory)

    /** 从 rootfs 内 ELF 二进制的 e_machine 字段探测架构; 失败兜底 arm64(Android 设备主流) */
    private fun detectRootfsArch(linuxDir: File): String {
        for (rel in ARCH_SNIFF_BINARIES) {
            val file = runCatching { File(linuxDir, rel).canonicalFile }.getOrDefault(File(linuxDir, rel))
            if (!file.isFile || file.length() < 20L) continue
            val machine = runCatching {
                RandomAccessFile(file, "r").use { raf ->
                    val header = ByteArray(20)
                    if (raf.read(header) != 20) return@use -1
                    if ((header[0].toInt() and 0xff) != 0x7f ||
                        (header[1].toInt() and 0xff) != 0x45 ||
                        (header[2].toInt() and 0xff) != 0x4c ||
                        (header[3].toInt() and 0xff) != 0x46
                    ) {
                        return@use -1
                    }
                    (header[18].toInt() and 0xff) or ((header[19].toInt() and 0xff) shl 8)
                }
            }.getOrDefault(-1)
            when (machine) {
                183 -> return "arm64"
                62 -> return "x86_64"
                40 -> return "arm"
                3, 8 -> return "x86"
            }
        }
        return "arm64"
    }

    /** 文件内任一 Ubuntu 套件基名命中 EOL 名单即视为 EOL 版本源 */
    private fun hasEolUbuntuSuite(file: File): Boolean {
        val text = file.readText()
        val suites = if (file.extension == "sources") {
            text.lineSequence()
                .filter { it.trimStart().startsWith("Suites:") }
                .flatMap { it.trim().removePrefix("Suites:").trim().split(WHITESPACE_REGEX) }
                .toList()
        } else {
            APT_SOURCE_LINE_REGEX.findAll(text).map { it.groupValues[3] }.toList()
        }
        return suites.any { it.substringBefore('-') in EOL_UBUNTU_CODENAMES }
    }

    private fun ensureApkMirror(linuxDir: File) {
        val reposFile = File(linuxDir, "etc/apk/repositories")
        if (!reposFile.isFile) return
        val text = reposFile.readText()
        if (text.contains("mirrors")) return
        val patched = text.replace(APK_REPO_REGEX) { m ->
            val distroPath = m.groupValues[1]
            "https://mirrors.aliyun.com/alpine/$distroPath"
        }
        if (patched != text) {
            reposFile.writeText(patched)
            Log.i(TAG, "Patched apk repositories: ${reposFile.name}")
        }
    }

    private fun patchOneLineSource(file: File, ubuntuBase: String, eolUbuntu: Boolean) {
        val text = file.readText()
        val patched = rewriteTextPreserveNewline(text) { line ->
            rewriteOneLineSource(line, ubuntuBase, eolUbuntu)
        }
        if (patched != text) {
            file.writeText(patched)
            Log.i(TAG, "Patched apt one-line source: ${file.name}")
        }
    }

    /** 逐行重写; lineSequence 按 split 语义保留行尾空元素, joinToString 可完整还原行尾换行 */
    private fun rewriteTextPreserveNewline(text: String, transform: (String) -> String): String =
        text.lineSequence().joinToString("\n") { transform(it) }

    /** 单行源重写: EOL 的 pocket 套件(updates/security/backports)在 old-releases 不存在, 整行注释掉 */
    private fun rewriteOneLineSource(line: String, ubuntuBase: String, eolUbuntu: Boolean): String {
        val m = APT_SOURCE_LINE_REGEX.find(line) ?: return line
        val uri = m.groupValues[2]
        val suite = m.groupValues[3]
        val isUbuntu = isUbuntuHost(uri)
        if (isUbuntu && eolUbuntu && suite.contains('-') && suite.substringBefore('-') in EOL_UBUNTU_CODENAMES) {
            return "# $line"
        }
        val newUri = rewriteAptUri(uri, ubuntuBase, eolUbuntu) ?: return line
        return line.replaceRange(m.groups[2]!!.range, newUri)
    }

    private fun patchDeb822Source(file: File, ubuntuBase: String, eolUbuntu: Boolean) {
        val text = file.readText()
        val patched = rewriteTextPreserveNewline(text) { line ->
            when {
                line.trimStart().startsWith("URIs:") -> {
                    val uris = line.trim().removePrefix("URIs:").trim().split(WHITESPACE_REGEX)
                    val newUris = uris.joinToString(" ") { rewriteAptUri(it, ubuntuBase, eolUbuntu) ?: it }
                    if (newUris == uris.joinToString(" ")) line else "URIs: $newUris"
                }
                eolUbuntu && line.trimStart().startsWith("Suites:") -> {
                    val suites = line.trim().removePrefix("Suites:").trim().split(WHITESPACE_REGEX)
                    val kept = suites.filter {
                        it.substringBefore('-') !in EOL_UBUNTU_CODENAMES || !it.contains('-')
                    }.ifEmpty { suites.map { it.substringBefore('-') }.distinct() }
                    if (kept == suites) line else "Suites: ${kept.joinToString(" ")}"
                }
                else -> line
            }
        }
        if (patched != text) {
            file.writeText(patched)
            Log.i(TAG, "Patched apt Deb822 source: ${file.name}")
        }
    }

    private fun isUbuntuHost(uri: String): Boolean {
        val host = uri.substringAfter("://", "").substringBefore('/').lowercase()
        return host in OFFICIAL_UBUNTU_HOSTS || (host == TUNA_HOST && uri.contains("ubuntu"))
    }

    /**
     * apt 源 URI 重写引擎, 返回 null 表示保持原样:
     * - Ubuntu/Debian 官方域名换 TUNA 对应镜像(arm64 走 ubuntu-ports; EOL 走 ubuntu-old-releases)
     * - 修正历史误 patch(arm64 源曾被写到 amd64 档案 /ubuntu/)
     * - 用户自配镜像域名(mirrors.*)尊重不动
     */
    private fun rewriteAptUri(uri: String, ubuntuBase: String, eolUbuntu: Boolean): String? {
        val schemeEnd = uri.indexOf("://")
        if (schemeEnd <= 0) return null
        val rest = uri.substring(schemeEnd + 3)
        val host = rest.substringBefore('/').lowercase()
        val path = "/" + rest.substringAfter('/', "").trimEnd('/')
        val targetPath = "/" + ubuntuBase.substringAfter("://").substringAfter('/').trimEnd('/')
        return when {
            host in OFFICIAL_UBUNTU_HOSTS -> ubuntuBase
            host in OFFICIAL_DEBIAN_HOSTS -> ubuntuBase.substringBefore("://") + "://$TUNA_HOST/debian/"
            host == TUNA_HOST -> when {
                path == targetPath -> null
                (path == "/ubuntu" || path == "/ubuntu-ports") && eolUbuntu -> ubuntuBase
                path == "/ubuntu" && targetPath == "/ubuntu-ports" -> ubuntuBase
                path == "/ubuntu-ports" && targetPath == "/ubuntu" -> ubuntuBase
                else -> null
            }
            host.contains("mirror") -> null
            else -> null
        }
    }

    private fun verifyWrite(file: File, label: String) {
        if (!file.isFile || file.length() == 0L) {
            Log.w(TAG, "Patch write may have failed for $label: ${file.absolutePath} " +
                "(exists=${file.isFile}, length=${file.length()})")
        }
    }

    private companion object {
        private const val TAG = "RootfsPatcher"
        private const val MAX_DNS_SERVERS = 3
        private const val DEFAULT_HOSTNAME = "localhost"
        private const val TUNA_HOST = "mirrors.tuna.tsinghua.edu.cn"

        /** Ubuntu 官方 apt 域名(arm64 镜像源指向 ports.ubuntu.com) */
        private val OFFICIAL_UBUNTU_HOSTS = setOf(
            "archive.ubuntu.com",
            "security.ubuntu.com",
            "ports.ubuntu.com",
            "old-releases.ubuntu.com",
        )
        private val OFFICIAL_DEBIAN_HOSTS = setOf(
            "deb.debian.org",
            "security.debian.org",
        )

        /**
         * 已从 ports 下架、仅存于 old-releases 的 Ubuntu 代号(2026-09 实测; LTS 不在其中)。
         * 注意: EOL 日期与实际迁移不同步——questing(25.10)/plucky(25.04) 虽已停止支持,
         * 但 ports 上仍在, 故不列入, 否则会被错误重定向到 old-releases 而 404。
         */
        private val EOL_UBUNTU_CODENAMES = setOf(
            "oracular", // 24.10
            "mantic",   // 23.10
            "lunar",    // 23.04
            "kinetic",  // 22.10
            "impish",   // 21.10
            "hirsute",  // 21.04
            "groovy",   // 20.10
        )

        /** 架构探测候选: 依序尝试, 第一个可读 ELF 的二进制生效 */
        private val ARCH_SNIFF_BINARIES = listOf(
            "bin/sh",
            "bin/busybox",
            "usr/bin/env",
            "usr/bin/apt-get",
            "usr/bin/dpkg",
            "usr/bin/python3",
            "bin/mount",
        )
        private val WHITESPACE_REGEX = Regex("\\s+")
        private val DEFAULT_DNS_SERVERS = listOf(
            "223.5.5.5",
            "1.1.1.1",
            "8.8.8.8",
        )
        private val APT_SOURCE_LINE_REGEX = Regex(
            "^(deb|deb-src)\\s+(\\S+)\\s+(\\S+)",
            setOf(RegexOption.MULTILINE),
        )
        private val APK_REPO_REGEX = Regex(
            """https?://[^\s]*alpinelinux\.org/alpine/([^\s]*)"""
        )
    }
}

data class RootfsPatchOptions(
    val nameservers: List<String> = emptyList(),
    val hostname: String = "localhost",
    val locale: String = "C.UTF-8",
    val groupIds: List<Long> = emptyList(),
)
